config/routes.rb
Rails.application.routes.draw do

  devise_for :users 
  devise_scope :user do
    authenticated :user do
      root 'pets#new', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  resources :welcomes 
  resources :pets 

end

app/models/api_key.rb
class ApiKey < ActiveRecord::Base
	before_create :generate_access_token
private
  def generate_access_token
  	begin
  	self.access_token = SecureRandom.hex
   end while self.class.exists?(access_token: access_token)
  end	

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
end

app/models/home.rb
class Home < ActiveRecord::Base
end

app/models/pet.rb
class Pet < ActiveRecord::Base
	#validates_processing_of :image
mount_uploader :image, ImageUploader
validate :image_size_validation
 
private
  def image_size_validation
    errors[:image] << "should be less than 500KB" if image.size > 0.5.megabytes
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable# :confirmable

 #  attr_accessible :email, :password, :password_confirmation, :remember_me
                   
end

app/controllers/api/v1/products_controller.rb
module Api
  module V1
   class ProductsController < ApplicationController
   	  class Product < ::Product
   	  	def as_json(options={})
   	  		super.merge!(released_on: released_at.to_date)
   	  	end
   	 end 	
	    def index
		   
		 @product =  Product.all
		 render json: @product
	        end	
	   
   end
  end
end

app/controllers/api/v2/products_controller.rb
module Api
  module V2 
   class ProductsController < ApplicationController
    #http_basic_authenticate_with name: "sandeep", password: "secret"
    before_filter :restrict_access
   	 #  class Product < ::Product
   	 #  	# def as_json(options={})
   	 #  	# 	binding.pry
   	 #  	# 	super.merge!(released_on: released_at.to_date)
   	 #  	# end
   	 # end 	
	   def index
		   
		 @product =  Product.all
		 render json: @product
	        end	

     private     
	   def restrict_access
      # api_key = ApiKey.find_by_access_token(params[:access_token])
      # head :unauthorized unless api_key
      authenticate_or_request_with_http_token do |token,options|
        binding.pry
        ApiKey.exists?(access_token: token)
      end
     end

   end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  # GET /pets
  # GET /pets.json
  def index
    @pets = Pet.all
  end

  # GET /pets/1
  # GET /pets/1.json
  def show

  end

  def my_update
 
  end

  def my_edit
    
    @pet = Pet.last
    if @pet.update(name: params["name"])
     redirect_to @pet, notice: 'Pet was successfully updated.'
    end
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(pet_params)
    binding.pry
    PetMailer.welcome_email(@pet, current_user).deliver_now
    respond_to do |format|

      if @pet.save
        format.html { redirect_to @pet, notice: 'Pet was successfully created.' }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      binding.pry
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: 'Pet was successfully updated.' }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url, notice: 'Pet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      
      @pet = Pet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      #params.require(:pet).permit(:name, :description, :image)
      params.require(:pet).permit(:name, :description)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
    respond_to do |format|
    	format.html
    	format.json {render json: @products}
    end	
  end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController

  def new
  	@user = User.new
  end

  def create
  	u=User.new(user_params)
    if u.save
      flash[:success] = "Client added successfully"
      redirect_to welcomes_path
    else
      flash[:success] = "Client not added."
    end
  end

  def index
    
  end


  private

  def user_params
  	params.require(:user).permit!
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">  
  <title>MyApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "sample app", '#', id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",   new_pet_path %></li>
            <%id=7%>
            <li><%= link_to "Help",   pet_path("sdas") %></li>
            <li>
              <% if user_signed_in? %>
                <%= link_to "Log out",  destroy_user_session_path, method: :delete  %>
              <%else%>
                <%= link_to "Log in", '#' %>
              <%end%>  
            </li>
          </ul>
        </nav>
      </div>
</header>
<div class="container">
      <%= yield %>
    </div>
    <footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", "contact_path" %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>
    </div>

</body>
</html>

app/views/pets/_form.html.erb
<%= form_for @pet, html: { multipart: true } do |f| %>
  <% if @pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pet.errors.count, "error") %> prohibited this pet from being saved:</h2>
 
      <ul>
      <% @pet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
    <% if f.object.image? %>
      <%= image_tag f.object.image.thumb.url %>
      <%= f.label :remove_image %>
      <%= f.check_box :remove_image %> 
    <% end %>
  </div>
 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pets/edit.html.erb
<h1>Editing Pet</h1>

<%#= render 'form' %>

<%#= link_to 'Show', @pet %> |
<%#= link_to 'Back', pets_path %>

app/views/pets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pets.each do |pet| %>
      <tr>
        <td><%= pet.name %></td>
        <td><%= pet.description %></td>
        <td><%= pet.image %></td>
        <td><%= link_to 'Show', pet %></td>
        <td><%= link_to 'Edit', edit_pet_path(pet) %></td>
        <td><%= link_to 'Destroy', pet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pet', new_pet_path %>

app/views/pets/my_update.html.erb
<%= form_tag(my_edit_pets_path, method: :put) do %>

<%= text_field_tag 'name' %><br>
<%= text_field_tag 'desc' %><br>

<%= submit_tag "Confirm" %>
<% end %>

app/views/pets/new.html.erb
<h1>New Pet</h1>

<%= render 'form' %>

<%= link_to 'Back', pets_path %>

app/views/pets/show.html.erb
*app/views/pets/show.html.erb*
 
<p id="notice"><%= notice %></p>
 
<p>
  <strong>Name:</strong>
  <%= @pet.name %>
</p>
 
<p>
  <strong>Description:</strong>
  <%= @pet.description %>
</p>
 
<p>
  <strong>Image:</strong>
  <%= image_tag @pet.image.thumb.url %>
</p>
 
<%= link_to 'Edit', edit_pet_path(@pet) %> |
<%= link_to 'Back', pets_path %>

app/views/products/index.html.erb
<% @products.each do |product| %>
  <% cache product do %>
    <%= product.title %>
  <% end %>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

app/views/welcomes/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>


 <%= link_to "new", new_welcome_path %>


</br>
<%a=[1,2,3,4]%>
<%for i in a%>
  <%sp = a.length-1%>
  <%while(i<sp)%>
    <%=" "%>
    <%sp= sp-1%>
  <%end%>
  <%j=1%>

  <%while(i>=j)%>
    <%=("*")%>
    <%j=j+1%>
  <%end%>
</br>
<%end%>

app/views/welcomes/new.html.erb
<%= form_for @user, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
  <%= f.text_field :name %>

  <%= f.submit "Create" %>
<% end %>